In [5]:
import torch
import numpy as np
import time
from torch.nn import functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


cpu


In [ ]:
# measuring the difference between the cpu and the gpu
start

In [15]:
# %% time calcs the time it takes to execute a block
%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

# gpu v cpu
elapsed_time = end_time-start_time
print(f"{elapsed_time:0.8f}")

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.63 µs
0.00012851


In [10]:
# want to see if numpy on the gpu or to torch on the cpu
# utlilizing a bunch of tensors
# the gpu took les than half the time that the cpu took
# when have billions of parameters, not going to be doing very complex computations
# it will be like 3-4 dimensions. just need the cpu to do these. gives the tasks to // processes
# in order to be a ton quicker
# TAKEAWAY: // processes of gpu allows for training efficency
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print (f"{elapsed_time: .8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print (f"{elapsed_time: .8f}")

 0.75003695
 0.15074015


In [17]:
probablities = torch.tensor([0.1, 0.9])

samples = torch.multinomial(probablities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])


In [18]:
# torch.cat contatinates tensors
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [23]:
out = torch.tril(torch.ones(5,5))
out
# tril = triangle lower

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
out = torch.triu(torch.ones(5,5))
out
# tril = triangle upper

In [26]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out
# masekd fill: exp every element; if zero it is inf, if inf it is 0

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [27]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [28]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

# stack takes something that 1D and stack to make 2D (can use other dimensions too)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

# nn.Linear -> funciton of the nn module
# nn module -> contains anything with learnable parameters

tensor([5.0017, 0.7632, 0.8554], grad_fn=<SqueezeBackward4>)


In [35]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [36]:
# intalize an embedding layer
vocab_size = 1000
embedding_data = 100
embedding = nn.Embedding(vocab_size, embedding_data)

# create some input indices
input_indices = torch.LongTensor([1,5,3,2])

# apply embedding layer
embedded_output = embedding(input_indices)

# the output will be a tensor of shape (4,100) where 4 is # inputs and 100 is the 
# dimensionality of the embdedding vector
print(embedded_output.shape)

torch.Size([4, 100])


In [5]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
c = a@b
print(c)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [12]:
int_64 = torch.randint(1,(3,10)).float() # (range (0-1), shape of matrix)
float_32 = torch.rand(10,3)
result = torch.matmul(int_64, float_32)
print(result) # cannot do this bc int and float are same data type

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [2]:
a = torch.rand(2,3,5)
print(a)
print(a.shape)
# unpacks the shape so x=2, y=3, z=5
x,y,z = a.shape
# a.view makes that tensor again with those cords
a = a.view(x,y,z)
print(x,y,z)
print(a.shape)

tensor([[[0.2498, 0.2364, 0.2885, 0.4783, 0.5106],
         [0.3301, 0.4777, 0.1358, 0.0431, 0.3764],
         [0.7518, 0.3403, 0.3054, 0.0773, 0.2830]],

        [[0.3901, 0.9139, 0.7120, 0.5065, 0.9258],
         [0.6050, 0.8640, 0.6631, 0.3834, 0.0047],
         [0.4234, 0.8649, 0.5905, 0.1797, 0.4932]]])
torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [6]:
input = torch.rand((4,8,10))
B,T,C = input.shape
output = input.view(B*T, C)
print(output)
print(output[:,-1,:])

tensor([[0.5416, 0.9952, 0.9560, 0.2760, 0.2862, 0.8726, 0.5031, 0.0324, 0.7371,
         0.9933],
        [0.0482, 0.8307, 0.7737, 0.2867, 0.2980, 0.7171, 0.1721, 0.0382, 0.8690,
         0.2833],
        [0.2010, 0.2579, 0.9852, 0.4673, 0.4356, 0.6062, 0.9033, 0.3328, 0.9590,
         0.1350],
        [0.5910, 0.3440, 0.3771, 0.9234, 0.8452, 0.5253, 0.7899, 0.0546, 0.6490,
         0.5085],
        [0.2499, 0.0719, 0.2585, 0.9537, 0.9784, 0.5421, 0.4592, 0.8324, 0.4453,
         0.0384],
        [0.7789, 0.4967, 0.5955, 0.0662, 0.6437, 0.8223, 0.7855, 0.6345, 0.8517,
         0.4230],
        [0.2938, 0.9082, 0.2802, 0.8997, 0.1308, 0.8322, 0.8551, 0.6874, 0.9523,
         0.9282],
        [0.9026, 0.0408, 0.9551, 0.7872, 0.6458, 0.7746, 0.7143, 0.9001, 0.5232,
         0.7341],
        [0.6802, 0.1948, 0.3686, 0.9060, 0.3576, 0.7487, 0.8409, 0.7693, 0.8474,
         0.7102],
        [0.6681, 0.7408, 0.2128, 0.0662, 0.4923, 0.1016, 0.2543, 0.1635, 0.7396,
         0.4369],
        [0

IndexError: too many indices for tensor of dimension 2

In [12]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)
# relu: if the number is below 0, changes to 0. if above 0, stays the same

tensor([1.])
