In [2]:
import torch

In [3]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 22, -68, -36, -22, -17,  50])

In [5]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [6]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
input = torch.empty(2, 3)
input
# these are either very large or very small numbers

tensor([[4.0911e-41, 0.0000e+00, 1.1778e-34],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])

In [10]:
arrange = torch.arange(5)
arrange

tensor([0, 1, 2, 3, 4])

In [11]:
linspace = torch.linspace(3,10, steps=5)
linspace
# getting constant increments from 3-10 taking 5 equal steps
# cool!

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [13]:
logspace = torch.logspace(start = -10, end = 10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [14]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
a = torch.empty(2,3, dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[120279024, 120375296,         1],
        [        0,        96,        80]])